[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p staticfiles"
]

[start]
cmd = "gunicorn App.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
