[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn App.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
